version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_ENV=venv
      - PATH=writeordie/venv/bin:$PATH

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
